404-DriverNotFound/backend-b

- .dockerignore
build과정중 copy와 관련 불필요한 파일들 작성
./git*
./node_modules
./dist
> ⚠️ 이슈 없이 Pull Request 금지  
> 아래 항목은 필수이지만, 필요없다고 생각하는 부분은 삭제하고 필요한 부분은 자유롭게 추가 가능
container 빌드과정 중 copy와 관련해 불필요한 파일들이 복사되는것을 막기 위해 작성
어떤 테스트를 했는지 간단히 설명해주세요.
http://pyrasis.com/book/DockerForTheReallyImpatient/Chapter07/01
해결한 이슈 번호를 기재해주세요.  
[feat] 이슈를 해결했을 경우 close #issue-number  
[fix] 이슈를 해결했을 경우 fix #issue-number
> Chore: dockerignore 작성#6

- .dockerignore
- Dockerfile
Dockerfile 작성
.dockerignore에서 git 관련 파일들이 업로드 되지 않도록 수정
.dockerignore 작성 내용에 따라 컨테이너 내부에 파일이 COPY 되는지 되지 않는지 확인함.
해결한 이슈 번호를 기재해주세요.  
[feat] 이슈를 해결했을 경우 close #issue-number  
[fix] 이슈를 해결했을 경우 fix #issue-number
> Chore: Dockerfile 작성#6

- Dockerfile
- src/main.ts
프론트와 포트 조율을 위해 port를 3000 -> 5000으로 수정
close #17
> Fix: port 번호 수정

- .env.stage.dev
- .env.stage.prod
- Dockerfile
#21 에 이야기한 내용처럼,
`docker-compose`로 배포할 때, `DB_HOST`를 매번 변경해주어야하는 번거로움이 있어, 
Dockerfile 일부와 환경변수 일부 수정하였습니다.
`build` + `run` 테스트 완료
fix #21
> Fix: Dockerfile을 production 환경으로 실행(#21)

- src/auth/auth.controller.ts
- src/auth/guards/ft-oauth.guard.ts
- src/auth/guards/user-created.guard.ts
- src/users/users.controller.ts
Guard의 이름을 아래와 같이 바꾸었어요.
NameGuard만 수정하려 했는데, FtGuard도 이름을 바꾸는게 나을것같아서 수정했습니다.
```
NameGuard -> UserCreatedGuard
FtGuard -> FtOauthGuard
```
빌드만 확인했는데, 이름만 바꾼 것이라 큰 문제는 없을 것같습니다.
close  #52
> Fix: Guard 이름 수정(#52)

- src/users/dto/update-user.dto.ts
- src/users/user-status.enum.ts
- src/users/user.entity.ts
- src/users/users.repository.ts
`User` entity에 `status` 칼럼을 추가하고 `PATCH` `/users/me`에 `status` 변경가능하게 추가
close #34
> Feat: User entity에 Status 칼럼 추가(#34)

- src/events/events.gateway.ts
- src/events/events.module.ts
소켓 연결    시 user status 가  online으로 설정됨.
소켓 연결해제시 user status 가 offline으로 설정됨.
DB 수정 여부 확인.
fix #34
> Fix: 소켓 연결 상태로 온라인 오프라인되도록 수정(#34)

- src/events/events.gateway.ts
`join` to `joinRoom` : 전체 채널 join에서 특정 채널만 join 하도록 수정
`leaveRoom` : 특정 채널만 leave하는 이벤트 추가
별도로 테스트해본 내용이 없어서 프론트엔드와 연결시 확인할 수 있을 것으로 기대됩니다.
x
> Fix: `join` event를 특정 채널만 join하는 이벤트로 수정

- src/channels/channels.service.ts
에러 메시지 변경 요청이 있어서 수정했습니다.
https://42born2code.slack.com/archives/C028H0MJULC/p1631520699007700?thread_ts=1631513137.006400&cid=C028H0MJULC
message: `You are ${role} in this channel.`
> Fix: 유저를 추가하는 API에서 에러 메시지 수정

- src/app.service.ts
- src/main.ts
- src/users/dto/create-user.dto.ts
- src/users/dto/update-user.dto.ts
- src/users/users.controller.ts
- src/users/users.repository.ts
- src/users/users.service.ts
enable2FA가 string으로 처리되고 있어서 boolean으로 수정하였습니다.
기본적인 테스트는 해봤는데, 놓친 부분이 있을수도있어요.
close #73
> Fix: enable2FA를 boolean으로 변경

- src/channels/channels.controller.ts
- src/channels/channels.service.ts
- src/channels/entities/membership.entity.ts
1. mutedAt을 unmutedAt으로 수정하였음.
2.  음소거를 해제하는 API 추가.
3. 1분이 지나면 unmutedAt이 null로 설정되도록 수정.
> Fix: mute 로직 수정

- src/channels/channels.service.ts
mute와 unmute에서 안되는 케이스를 exception 했던 방식에서
되는 케이스를 추려서 나머지를 exception하는 방식으로 수정했습니다.
> Refactor: mute API 예외 케이스 수정

- src/channels/channels.service.ts
> ⚠️ 이슈 없이 Pull Request 금지  
> 아래 항목은 필수이지만, 필요없다고 생각하는 부분은 삭제하고 필요한 부분은 자유롭게 추가 가능
기존 반례로 된 조건문을 허용하는 것들만 통과시키는 로직으로 변경
다만 중복되는 로직이 많아서 몇몇 부분은 함수화가 필요할것 같습니다.
해결한 이슈 번호를 기재해주세요.  
[feat] 이슈를 해결했을 경우 close #issue-number  
[fix] 이슈를 해결했을 경우 fix #issue-number
> Refactor: MemberRole API 예외 케이스 수정

- src/seeder.ts
User와 관련된 repository를 추가했더니 해결되었습니다.
근데 docker-compose 빌드할때는 문제가 없다고 나왔어서, 그 점은 조금 이상한 것같아요.
그리고 추후에 user와 연관된 테이블이 생겼을때, seeder에도 추가해줘야 합니당(이번에 바뀐 부분에)!
docker-compose로 띄웠을때 데이터 들어가는것 확인함.
close #96
> Fix: seeder에 User와 관련된 repository 추가

- src/users/repositories/users.repository.ts
- src/users/users.controller.ts
enable2FA 오작동을 수정했습니다.
close #98
> Fix: `PATCH` `/users/me` API에서 enable2FA 오작동 수정

- src/events/events.gateway.ts
- src/events/events.service.ts
- src/events/games/dto/on-match-type-mode.dto.ts
- src/events/games/lobby-manager.service.ts
- src/events/games/room-manager.service.ts
매칭 타입과 모드에 따라 매칭이 일어날수 있는 로직
1. 두 사람이 다른 게임 모드를 선택했을때 매칭이 안일어나는지 확인 (O)
2. 두 사람이 같은 게임 모드를  선택했을때 매칭이 일어나는지 확인 (O)
3. DB에 해당하는 타입과 모드로 매칭기록이 저장되는지 확인 (O)
close #109 #112 #113
> Feat/game matching  (#109)

- src/events/games/classes/ball.class.ts
- src/events/games/classes/base.class.ts
- src/events/games/classes/player.class.ts
- src/events/games/classes/room.class.ts
- src/events/games/room-manager.service.ts
게임모드인 REVERSE, SPEED일때 방의 특성 변경.
close #114
> Feat: GameMode 반영 (#114)

- src/events/games/classes/room.class.ts
- src/events/games/room-manager.service.ts
exhibition 타입은 전적에 반영되지 않도록 수정했어요!
그리고 필요없어보이는 콘솔로그도 지웠습니다!
close #116
> Fix: exhibition type 게임은 스코어와 전적에 반영되지 않도록 수정

- src/events/events.gateway.ts
- src/events/events.service.ts
- src/events/games/dto/invite-match.dto.ts
매치 초대 부분 초안을 작성했습니다. 프론트엔드와도 어느정도 맞추어보았는데 디테일하게 더 수정해야할 부분이 있습니다.
See also: #44
> Feat: 매치 초대 기능 추가

- src/events/events.service.ts
모든 소켓이 아니라 마지막 연결된 소켓에 연결하도록 처리했습니다.
@Jack-R-lantern 님 믿고 유닛테스트 생략! ㅎㅎ..
close: #120
> Fix: 초대에서 소켓 이벤트를 보낼 때 모든 소켓에 다 보내는 문제 수정

- package.json
- src/users/constants/multer.options.ts
- src/users/users.controller.ts
- yarn.lock
파일명에 유저이름을 사용하지 않고, uuidv4 + timestamp를 사용하는 방식으로 수정함.
close #30
> Fix: 유저 생성시 파일명에 undefined가 붙는 문제 수정

- src/events/events.gateway.ts
- src/events/events.service.ts
- src/events/games/classes/room.class.ts
- src/events/games/constants/player-position.enum.ts
- src/events/games/room-manager.service.ts
매치를 관전할 수 있는 기능입니다.
소켓이 전송이 느려질 때를 제외하고 충분히 테스트했다고 생각해요.
close: #50
> Feat: 게임 관전기능 추가
